name: 'Infrastructure as automation'
description: 'Upper automated terraform infrastructure orchestrator'
inputs:
  terragrunt_options:
    description: 'Terragrunt additional options'
    required: true
    default: --terragrunt-debug
  path:
    description: 'Which directory to use as context'
    required: true
    default: ''
  known_hosts:
    description: 'Known hosts to checkout modules using git ssh uri scheme'
    required: false
    default: github.com
  ssh_private_key:
    description: 'SSH private key to use to checkout modules from git'
    required: false
    default: ''
outputs:
  state_output:
    description: 'JSON string with outputs from latest infrastructure state change'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - terragrunt_apply
    - CONTEXT_PATH=${{ inputs.context_path }}
    - TERRAGRUNT_OPTIONS=${{ inputs.terragrunt_options }}
    - KNOWN_HOSTS=${{ inputs.known_hosts }}
    - SSH_PRIVATE_KEY=${{ inputs.ssh_private_key }}