name: Production (main.yml)

on:
  push:
    branches:
      - main

jobs:

  apply:
    name: Apply shared infrastructure
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create configuration files
        shell: bash
        env:
          GCP_JSON_CREDENTIALS: ${{ secrets.GCP_JSON_CREDENTIALS }}
          OWNER_HCL: ${{ secrets.OWNER_HCL }}
        run: |
          echo "$GCP_JSON_CREDENTIALS" > gcp_credentials.json
          echo "$OWNER_HCL" > owner.hcl
          ls -lah
          echo $GITHUB_WORKSPACE

      - name: Apply deploy/prd folder
        uses: ./
        id: apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_credentials.json
        with:
          path: deploy/prd